In [13]:
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
from scipy.stats import qmc
from scipy.stats import norm

Grundsätzliche Parameter festlegen

In [161]:
T = 1
d = 2
delta_t = T/d

S_0 = 100
mu = 0.045
sigma = 0.3


Standard Brownian Motion Simulation

In [162]:
def create_standard_bm(d, delta_t):
#create lower trinangular matrix with ones
    lower_tri_matr = np.tril(np.ones([d,d]))
    A = math.sqrt(delta_t)*lower_tri_matr
    #create Brownian motion
    w = A.dot(np.random.normal(0,1,d))

    return w
    #plt.plot(w)
    #plt.show()


Asset

In [163]:
def create_asset_prices(d, delta_t, S_0, mu, sigma):
    S = np.zeros(d+1) #+1 weil d mal simuliert wird und aber der Startpreis des Assets auch in dem Vektor steht
    S[0] = S_0
    delta_S = []

    w = create_standard_bm(d, delta_t)

    #erstelle gesamten Vekjtor w mit w_0
    delta_w = np.concatenate((w[0],np.diff(w)),axis=None)

    for i in range(d):
        delta_S.append(mu*S[i]*delta_t + sigma*S[i]*delta_w[i])
        S[i+1] = S[i] + delta_S[i]

    return S
    
    '''
    plt.plot(s)
    plt.title("Asset prices for mu = " + str(mu) + ", S_0 = " + str(s_0) + ", Sigma = " + str(sigma))
    plt.ylabel("Asset prices")
    plt.show()
    '''


Test, ob Asset prices richtig modelliert sind. Vergleich mit exakter Berechnung ergibt, dass Ergebnis stimmt.

In [164]:
number_paths = 10000
mc_vector = np.empty(number_paths)
for i in range(number_paths):
    mc_vector[i] = create_asset_prices(d, delta_t, S_0, mu, sigma)[2]
display(np.average(mc_vector))

display(S_0*math.exp(mu*d*delta_t))

104.03143789097915

104.6027859908717

In [165]:
#WICHTIG: S_0 muss im Vektor S sein!!! (per Definition)
def ratched_option(d, delta_t, S_0, mu, sigma): 
    S = create_asset_prices(d, delta_t, S_0, mu, sigma)
    #display(S)
    #indic = np.array([1 if s > 0 else 0 for s in np.diff(S)])
    indic = np.diff(S)>0
    #display(indic)
    payoff = np.average(indic*S[1:(S.size)])  #python spezifisch fehlt dann das erste Element
    display(S)
    display(S[1:(S.size)])
    return payoff

In [160]:
ratched_option(d, delta_t, S_0, mu, sigma)

array([100.        ,  53.11320996,  60.84631441])

array([53.11320996, 60.84631441])

30.42315720324412

# Monte Carlo Simulation

Exaktes Ergebnis

In [166]:
Exp = (S_0/d)*norm.cdf((mu-((sigma**2)/2))*math.sqrt(delta_t)/sigma+sigma*math.sqrt(delta_t))*np.sum(np.exp(mu*delta_t*(np.array(range(d))+1)))
display(Exp)

60.40825215088241

Monte Carlo Simulation

In [167]:
number_paths = 1000
mc_vector = np.empty(number_paths)
for i in range(number_paths):
    mc_vector[i] = ratched_option(d, delta_t, S_0, mu, sigma)
np.average(mc_vector)

array([100.        , 118.13044634, 118.07192781])

array([118.13044634, 118.07192781])

array([100.        ,  94.16971803, 120.40878517])

array([ 94.16971803, 120.40878517])

array([100.        ,  99.03677473, 121.30583026])

array([ 99.03677473, 121.30583026])

array([100.        , 107.25649374,  60.12600577])

array([107.25649374,  60.12600577])

array([100.        , 127.67179017, 138.7301392 ])

array([127.67179017, 138.7301392 ])

array([100.        , 100.31161463, 101.67608962])

array([100.31161463, 101.67608962])

array([100.        , 109.54146518, 123.22245305])

array([109.54146518, 123.22245305])

array([100.        ,  78.69720948,  76.57778941])

array([78.69720948, 76.57778941])

array([100.        , 115.50973719, 146.88863117])

array([115.50973719, 146.88863117])

array([100.        , 103.48776942,  86.2024562 ])

array([103.48776942,  86.2024562 ])

array([100.        , 101.32018099, 103.81426836])

array([101.32018099, 103.81426836])

array([100.        ,  83.08803825, 100.80361262])

array([ 83.08803825, 100.80361262])

array([100.        , 120.92978579, 135.46624453])

array([120.92978579, 135.46624453])

array([100.       ,  82.4966348,  77.0933336])

array([82.4966348, 77.0933336])

array([100.        , 128.9364202 , 121.82421874])

array([128.9364202 , 121.82421874])

array([100.        ,  93.76157483, 118.49240399])

array([ 93.76157483, 118.49240399])

array([100.        , 115.55500646, 138.35121834])

array([115.55500646, 138.35121834])

array([100.        , 149.10591246, 118.62115194])

array([149.10591246, 118.62115194])

array([100.        , 120.07555594, 148.13093857])

array([120.07555594, 148.13093857])

array([100.        , 122.77678344, 115.37386066])

array([122.77678344, 115.37386066])

array([100.        , 110.6872853 , 120.80639408])

array([110.6872853 , 120.80639408])

array([100.        ,  81.46474535, 114.60696598])

array([ 81.46474535, 114.60696598])

array([100.        ,  98.0138389 ,  89.42525063])

array([98.0138389 , 89.42525063])

array([100.        , 117.29640633,  98.26078983])

array([117.29640633,  98.26078983])

array([100.        , 105.73515724,  92.8016914 ])

array([105.73515724,  92.8016914 ])

array([100.        ,  82.3090916 ,  70.15835384])

array([82.3090916 , 70.15835384])

array([100.        , 122.55949878, 185.66328605])

array([122.55949878, 185.66328605])

array([100.        , 108.39354125, 120.52078598])

array([108.39354125, 120.52078598])

array([100.        , 126.16753196, 138.95745915])

array([126.16753196, 138.95745915])

array([100.        , 126.29185065, 160.34536012])

array([126.29185065, 160.34536012])

array([100.        , 107.35099389, 110.30644131])

array([107.35099389, 110.30644131])

array([100.        ,  91.228279  , 109.29003174])

array([ 91.228279  , 109.29003174])

array([100.        , 133.83104335, 114.08208227])

array([133.83104335, 114.08208227])

array([100.        ,  98.72322129, 110.3005457 ])

array([ 98.72322129, 110.3005457 ])

array([100.        ,  87.12018521,  66.25331177])

array([87.12018521, 66.25331177])

array([100.        , 105.16737028, 116.33919453])

array([105.16737028, 116.33919453])

array([100.        ,  68.92824799,  59.99130881])

array([68.92824799, 59.99130881])

array([100.        , 105.20822463, 107.95077352])

array([105.20822463, 107.95077352])

array([100.        , 106.94196313, 104.25814695])

array([106.94196313, 104.25814695])

array([100.        , 147.99748351, 179.10662722])

array([147.99748351, 179.10662722])

array([100.        , 102.24709091, 117.06757962])

array([102.24709091, 117.06757962])

array([100.        , 104.50824539, 111.56024698])

array([104.50824539, 111.56024698])

array([100.        ,  56.92827237,  44.38872281])

array([56.92827237, 44.38872281])

array([100.        , 145.11347793, 137.88568162])

array([145.11347793, 137.88568162])

array([100.        , 141.23124087, 112.31169561])

array([141.23124087, 112.31169561])

array([100.        , 122.25506644, 150.30835701])

array([122.25506644, 150.30835701])

array([100.        , 102.49140795, 112.31151507])

array([102.49140795, 112.31151507])

array([100.        , 120.62257675, 136.24353007])

array([120.62257675, 136.24353007])

array([100.        ,  94.64390037,  64.22469656])

array([94.64390037, 64.22469656])

array([100.        , 115.01105678, 112.75686521])

array([115.01105678, 112.75686521])

array([100.        , 125.76710875,  84.45602571])

array([125.76710875,  84.45602571])

array([100.        , 120.50702165,  78.09945779])

array([120.50702165,  78.09945779])

array([100.        ,  87.97111408,  98.29298052])

array([87.97111408, 98.29298052])

array([100.        ,  95.27173843,  95.02932593])

array([95.27173843, 95.02932593])

array([100.        , 101.68234756,  80.18412341])

array([101.68234756,  80.18412341])

array([100.        , 121.14075123, 155.20316526])

array([121.14075123, 155.20316526])

array([100.        , 125.38677307, 114.62203785])

array([125.38677307, 114.62203785])

array([100.        , 114.75601251,  96.53544626])

array([114.75601251,  96.53544626])

array([100.       , 104.886535 ,  79.6412411])

array([104.886535 ,  79.6412411])

array([100.        ,  60.73282699,  49.45973434])

array([60.73282699, 49.45973434])

array([100.        , 121.33503618, 121.04546283])

array([121.33503618, 121.04546283])

array([100.        , 114.61722908, 110.54764112])

array([114.61722908, 110.54764112])

array([100.        ,  80.79040335,  84.1129212 ])

array([80.79040335, 84.1129212 ])

array([100.        , 124.23096599, 103.67040861])

array([124.23096599, 103.67040861])

array([100.        ,  93.85995054,  72.7259751 ])

array([93.85995054, 72.7259751 ])

array([100.        , 141.54294531, 118.05181488])

array([141.54294531, 118.05181488])

array([100.        ,  77.69814282, 125.51172096])

array([ 77.69814282, 125.51172096])

array([100.        , 109.78452518, 106.22551146])

array([109.78452518, 106.22551146])

array([100.        ,  81.72629458,  86.89286398])

array([81.72629458, 86.89286398])

array([100.        ,  94.72200385,  96.34768197])

array([94.72200385, 96.34768197])

array([100.        , 118.38235   , 103.27246616])

array([118.38235   , 103.27246616])

array([100.        ,  82.4999746 ,  75.06393192])

array([82.4999746 , 75.06393192])

array([100.        ,  70.49481951,  68.66289384])

array([70.49481951, 68.66289384])

array([100.        ,  95.22400455,  42.91819408])

array([95.22400455, 42.91819408])

array([100.        , 121.52122505,  83.32464002])

array([121.52122505,  83.32464002])

array([100.        , 118.98595576, 182.37465477])

array([118.98595576, 182.37465477])

array([100.        , 102.15111068, 130.29837507])

array([102.15111068, 130.29837507])

array([100.        ,  69.18917845,  73.8016486 ])

array([69.18917845, 73.8016486 ])

array([100.        , 124.44891614, 146.59372304])

array([124.44891614, 146.59372304])

array([100.        ,  87.76251464,  79.05696523])

array([87.76251464, 79.05696523])

array([100.        , 121.50213637, 162.88602052])

array([121.50213637, 162.88602052])

array([100.        ,  80.48588834,  61.97827002])

array([80.48588834, 61.97827002])

array([100.        ,  93.19213855,  77.89571999])

array([93.19213855, 77.89571999])

array([100.        , 109.50247746, 109.45979778])

array([109.50247746, 109.45979778])

array([100.        ,  99.78417901,  92.88162356])

array([99.78417901, 92.88162356])

array([100.        , 100.7286258 , 106.72390784])

array([100.7286258 , 106.72390784])

array([100.        , 116.48063679, 134.62028404])

array([116.48063679, 134.62028404])

array([100.        ,  89.65293037, 120.32532687])

array([ 89.65293037, 120.32532687])

array([100.        , 148.97674867, 205.45996478])

array([148.97674867, 205.45996478])

array([100.        , 128.07005927,  83.11746704])

array([128.07005927,  83.11746704])

array([100.        ,  95.64296121, 115.9477622 ])

array([ 95.64296121, 115.9477622 ])

array([100.        , 118.9476616 , 137.62007083])

array([118.9476616 , 137.62007083])

array([100.        ,  97.80042933,  98.84676091])

array([97.80042933, 98.84676091])

array([100.        , 101.33098191,  64.51224398])

array([101.33098191,  64.51224398])

array([100.        , 129.75514412, 100.2264982 ])

array([129.75514412, 100.2264982 ])

array([100.        , 126.91665724, 114.38722042])

array([126.91665724, 114.38722042])

array([100.        ,  69.61408785,  78.8200057 ])

array([69.61408785, 78.8200057 ])

array([100.        , 110.25931872, 106.34133614])

array([110.25931872, 106.34133614])

array([100.        , 105.45412323,  73.18800749])

array([105.45412323,  73.18800749])

array([100.        , 125.36382393, 157.01339954])

array([125.36382393, 157.01339954])

array([100.        ,  86.61905775,  96.50231209])

array([86.61905775, 96.50231209])

array([100.        , 120.04242963, 158.26398491])

array([120.04242963, 158.26398491])

array([100.        , 119.94084043, 139.86627711])

array([119.94084043, 139.86627711])

array([100.        ,  71.09525123,  68.18991613])

array([71.09525123, 68.18991613])

array([100.        ,  75.47697678,  93.41148091])

array([75.47697678, 93.41148091])

array([100.        ,  89.92421549,  97.31538743])

array([89.92421549, 97.31538743])

array([100.        ,  67.26096023,  80.68947335])

array([67.26096023, 80.68947335])

array([100.        , 103.21859464,  95.85347547])

array([103.21859464,  95.85347547])

array([100.        ,  97.68015804,  93.75655991])

array([97.68015804, 93.75655991])

array([100.        ,  65.93308435,  63.39390804])

array([65.93308435, 63.39390804])

array([100.        ,  91.6092005 ,  92.16669324])

array([91.6092005 , 92.16669324])

array([100.        ,  77.59039077,  65.73988197])

array([77.59039077, 65.73988197])

array([100.        , 127.09320827, 132.52082476])

array([127.09320827, 132.52082476])

array([100.        , 103.75242244,  94.50650442])

array([103.75242244,  94.50650442])

array([100.        , 106.67466713, 134.22456857])

array([106.67466713, 134.22456857])

array([100.        , 119.23800813,  98.34645983])

array([119.23800813,  98.34645983])

array([100.        ,  97.64203649,  88.59100724])

array([97.64203649, 88.59100724])

array([100.        , 119.02495893, 129.47127561])

array([119.02495893, 129.47127561])

array([100.        ,  94.29331099,  78.2752158 ])

array([94.29331099, 78.2752158 ])

array([100.        ,  92.55829166,  91.07200164])

array([92.55829166, 91.07200164])

array([100.        , 129.92241975, 111.34790391])

array([129.92241975, 111.34790391])

array([100.        , 119.79844899, 111.68134271])

array([119.79844899, 111.68134271])

array([100.        , 123.76710992, 150.38747751])

array([123.76710992, 150.38747751])

array([100.        ,  71.70795577,  35.42323918])

array([71.70795577, 35.42323918])

array([100.        , 107.1436243 , 117.79987537])

array([107.1436243 , 117.79987537])

array([100.        , 108.50613532, 125.54448392])

array([108.50613532, 125.54448392])

array([100.        ,  91.70535815, 105.71029446])

array([ 91.70535815, 105.71029446])

array([100.        ,  91.90209549, 103.73204075])

array([ 91.90209549, 103.73204075])

array([100.        ,  95.04957553, 137.24352305])

array([ 95.04957553, 137.24352305])

array([100.        , 118.5667348 , 151.23829775])

array([118.5667348 , 151.23829775])

array([100.        , 135.68169629, 151.5378583 ])

array([135.68169629, 151.5378583 ])

array([100.        ,  81.78388716,  79.17769785])

array([81.78388716, 79.17769785])

array([100.        ,  98.95732323, 104.71473559])

array([ 98.95732323, 104.71473559])

array([100.        ,  71.94978256,  91.23987405])

array([71.94978256, 91.23987405])

array([100.        ,  74.02121827,  68.4537897 ])

array([74.02121827, 68.4537897 ])

array([100.        ,  88.42144826, 109.24698122])

array([ 88.42144826, 109.24698122])

array([100.        ,  96.28952647, 114.82476744])

array([ 96.28952647, 114.82476744])

array([100.        ,  63.08043923,  55.51462215])

array([63.08043923, 55.51462215])

array([100.        , 116.33453143, 140.97941334])

array([116.33453143, 140.97941334])

array([100.        , 105.30415697, 101.19783878])

array([105.30415697, 101.19783878])

array([100.        ,  86.06031343, 128.14091095])

array([ 86.06031343, 128.14091095])

array([100.        , 112.08994729, 157.18878671])

array([112.08994729, 157.18878671])

array([100.        , 118.70363541, 164.21479308])

array([118.70363541, 164.21479308])

array([100.        ,  64.14857094,  54.94711047])

array([64.14857094, 54.94711047])

array([100.        ,  85.47719907,  89.14857226])

array([85.47719907, 89.14857226])

array([100.        , 104.14284624, 100.96728285])

array([104.14284624, 100.96728285])

array([100.        , 115.76209463, 124.96603314])

array([115.76209463, 124.96603314])

array([100.        , 112.27073434, 128.13656525])

array([112.27073434, 128.13656525])

array([100.        , 124.10757766, 183.79128122])

array([124.10757766, 183.79128122])

array([100.        , 102.75206866, 106.85256999])

array([102.75206866, 106.85256999])

array([100.        ,  89.49074762,  82.89851703])

array([89.49074762, 82.89851703])

array([100.        ,  86.77119811, 108.7418784 ])

array([ 86.77119811, 108.7418784 ])

array([100.        , 106.80064923,  94.86063624])

array([106.80064923,  94.86063624])

array([100.        , 140.63888928, 120.97257178])

array([140.63888928, 120.97257178])

array([100.        ,  82.3499156 ,  90.76516037])

array([82.3499156 , 90.76516037])

array([100.        ,  95.50897033, 104.16908616])

array([ 95.50897033, 104.16908616])

array([100.        , 111.022827  , 135.87160629])

array([111.022827  , 135.87160629])

array([100.        , 101.04752233, 105.8902131 ])

array([101.04752233, 105.8902131 ])

array([100.        ,  96.78043233, 148.92812003])

array([ 96.78043233, 148.92812003])

array([100.        ,  62.03767386,  79.99875229])

array([62.03767386, 79.99875229])

array([100.        , 138.22552663, 124.05572949])

array([138.22552663, 124.05572949])

array([100.        ,  88.50900353,  87.45499679])

array([88.50900353, 87.45499679])

array([100.        , 102.40031728,  92.54314841])

array([102.40031728,  92.54314841])

array([100.        ,  73.80733413,  57.47026297])

array([73.80733413, 57.47026297])

array([100.        , 106.65658714, 111.26201211])

array([106.65658714, 111.26201211])

array([100.        , 108.448811  ,  66.46487361])

array([108.448811  ,  66.46487361])

array([100.        , 104.75402249, 121.23009728])

array([104.75402249, 121.23009728])

array([100.        ,  92.69158188,  98.29654068])

array([92.69158188, 98.29654068])

array([100.        ,  87.53948412,  60.48536354])

array([87.53948412, 60.48536354])

array([100.        ,  98.87576846,  88.29270111])

array([98.87576846, 88.29270111])

array([100.        , 122.96530375, 111.7758897 ])

array([122.96530375, 111.7758897 ])

array([100.        ,  96.94066079,  64.76215718])

array([96.94066079, 64.76215718])

array([100.        ,  86.62627853,  86.14203314])

array([86.62627853, 86.14203314])

array([100.        ,  74.09082958,  76.47448987])

array([74.09082958, 76.47448987])

array([100.        ,  91.72366528,  81.77620555])

array([91.72366528, 81.77620555])

array([100.        , 118.89906381, 122.5210682 ])

array([118.89906381, 122.5210682 ])

array([100.        ,  84.9863934 ,  84.34151608])

array([84.9863934 , 84.34151608])

array([100.        , 104.03887898,  99.20288373])

array([104.03887898,  99.20288373])

array([100.        , 122.0051497 , 107.50829495])

array([122.0051497 , 107.50829495])

array([100.        ,  95.91640734,  69.05319543])

array([95.91640734, 69.05319543])

array([100.        , 118.67896433,  76.78717819])

array([118.67896433,  76.78717819])

array([100.        ,  76.00101857,  93.77843856])

array([76.00101857, 93.77843856])

array([100.        , 101.85314285,  98.50257148])

array([101.85314285,  98.50257148])

array([100.        , 100.69612931, 121.20948946])

array([100.69612931, 121.20948946])

array([100.        , 135.36195824, 170.84660709])

array([135.36195824, 170.84660709])

array([100.        ,  98.27565   , 106.18203153])

array([ 98.27565   , 106.18203153])

array([100.        , 141.23953624, 112.31997279])

array([141.23953624, 112.31997279])

array([100.        ,  96.59038627,  98.91489104])

array([96.59038627, 98.91489104])

array([100.        ,  97.83992326,  97.06560079])

array([97.83992326, 97.06560079])

array([100.        , 125.13491474, 130.78336798])

array([125.13491474, 130.78336798])

array([100.        ,  66.13462113,  66.04785507])

array([66.13462113, 66.04785507])

array([100.        ,  90.43314719,  88.2773152 ])

array([90.43314719, 88.2773152 ])

array([100.        , 106.61737362, 152.8745851 ])

array([106.61737362, 152.8745851 ])

array([100.        , 109.65424751, 105.38582397])

array([109.65424751, 105.38582397])

array([100.        ,  74.90642473,  71.32829279])

array([74.90642473, 71.32829279])

array([100.        ,  64.52014428,  48.53123507])

array([64.52014428, 48.53123507])

array([100.        , 108.18955792,  75.95546476])

array([108.18955792,  75.95546476])

array([100.        ,  98.05687019, 102.59541724])

array([ 98.05687019, 102.59541724])

array([100.        , 111.43563624, 106.75461228])

array([111.43563624, 106.75461228])

array([100.        , 107.58405586, 106.82533366])

array([107.58405586, 106.82533366])

array([100.        ,  95.81414119, 110.78092082])

array([ 95.81414119, 110.78092082])

array([100.        ,  74.103168  ,  62.99676599])

array([74.103168  , 62.99676599])

array([100.        , 102.08295567,  80.79054369])

array([102.08295567,  80.79054369])

array([100.        , 128.37218095, 105.79422068])

array([128.37218095, 105.79422068])

array([100.        , 108.64352965, 107.02901351])

array([108.64352965, 107.02901351])

array([100.        , 105.3479399 , 115.51690803])

array([105.3479399 , 115.51690803])

array([100.        , 116.41717708, 149.52506799])

array([116.41717708, 149.52506799])

array([100.        ,  97.49898447,  88.24001249])

array([97.49898447, 88.24001249])

array([100.        ,  70.13018583,  74.16749213])

array([70.13018583, 74.16749213])

array([100.        , 126.87423207, 143.63320418])

array([126.87423207, 143.63320418])

array([100.        , 129.87668156, 129.43479784])

array([129.87668156, 129.43479784])

array([100.        , 104.56472832,  71.98915154])

array([104.56472832,  71.98915154])

array([100.        , 109.14683055,  92.99855028])

array([109.14683055,  92.99855028])

array([100.        , 104.67758272, 115.63901931])

array([104.67758272, 115.63901931])

array([100.        ,  76.26682076,  76.92287713])

array([76.26682076, 76.92287713])

array([100.        , 123.10316345, 114.90688061])

array([123.10316345, 114.90688061])

array([100.        ,  98.36332114,  66.83679917])

array([98.36332114, 66.83679917])

array([100.        , 101.66099124,  52.49919993])

array([101.66099124,  52.49919993])

array([100.        ,  96.54528421, 111.45337731])

array([ 96.54528421, 111.45337731])

array([100.        ,  57.43968641,  71.62552055])

array([57.43968641, 71.62552055])

array([100.        ,  88.36950857,  62.94381076])

array([88.36950857, 62.94381076])

array([100.        ,  96.27094593, 102.20769249])

array([ 96.27094593, 102.20769249])

array([100.        , 115.33229186, 104.21330725])

array([115.33229186, 104.21330725])

array([100.        , 110.10881158, 124.42023114])

array([110.10881158, 124.42023114])

array([100.        , 109.08322942, 167.5923713 ])

array([109.08322942, 167.5923713 ])

array([100.        ,  96.61988012,  70.80694012])

array([96.61988012, 70.80694012])

array([100.        , 101.01693317,  61.73443388])

array([101.01693317,  61.73443388])

array([100.        ,  68.80977161,  66.32105103])

array([68.80977161, 66.32105103])

array([100.        ,  83.66995714,  57.12884108])

array([83.66995714, 57.12884108])

array([100.        , 115.98614769, 121.18608029])

array([115.98614769, 121.18608029])

array([100.        , 100.90664507, 122.47819798])

array([100.90664507, 122.47819798])

array([100.        ,  78.94948128,  66.5222716 ])

array([78.94948128, 66.5222716 ])

array([100.        ,  96.450321  ,  93.02705619])

array([96.450321  , 93.02705619])

array([100.        , 109.95538118,  55.81676422])

array([109.95538118,  55.81676422])

array([100.        ,  56.88188809,  74.89934474])

array([56.88188809, 74.89934474])

array([100.        ,  83.99155848,  71.55511641])

array([83.99155848, 71.55511641])

array([100.        , 100.14408539,  74.1966823 ])

array([100.14408539,  74.1966823 ])

array([100.        ,  97.53660623,  54.44008352])

array([97.53660623, 54.44008352])

array([100.        , 120.78010082, 106.17239808])

array([120.78010082, 106.17239808])

array([100.        ,  74.14674217,  72.0227319 ])

array([74.14674217, 72.0227319 ])

array([100.        , 115.8887993 , 128.21699463])

array([115.8887993 , 128.21699463])

array([100.        ,  89.17834787, 106.07513917])

array([ 89.17834787, 106.07513917])

array([100.        , 129.76434876, 191.37297469])

array([129.76434876, 191.37297469])

array([100.        , 127.71347691, 134.1082926 ])

array([127.71347691, 134.1082926 ])

array([100.        , 104.14466986,  88.15083894])

array([104.14466986,  88.15083894])

array([100.        ,  89.27310867,  86.58296789])

array([89.27310867, 86.58296789])

array([100.        ,  59.88293145,  48.3947502 ])

array([59.88293145, 48.3947502 ])

array([100.        , 126.40864271, 140.17496798])

array([126.40864271, 140.17496798])

array([100.        , 126.77113884, 132.43977784])

array([126.77113884, 132.43977784])

array([100.        , 101.06120712,  88.99009414])

array([101.06120712,  88.99009414])

array([100.        , 136.3881328 , 121.47879567])

array([136.3881328 , 121.47879567])

array([100.        , 136.11476042, 135.60349429])

array([136.11476042, 135.60349429])

array([100.        ,  74.53185986,  85.80188811])

array([74.53185986, 85.80188811])

array([100.        ,  64.9029936 ,  90.46572355])

array([64.9029936 , 90.46572355])

array([100.        , 115.35552917, 113.22512856])

array([115.35552917, 113.22512856])

array([100.        , 103.01417048, 113.88181156])

array([103.01417048, 113.88181156])

array([100.        , 147.3749485 ,  93.42118601])

array([147.3749485 ,  93.42118601])

array([100.        , 113.76263049, 111.12057081])

array([113.76263049, 111.12057081])

array([100.        , 140.59120386, 111.79693519])

array([140.59120386, 111.79693519])

array([100.        , 153.63296535, 148.82141399])

array([153.63296535, 148.82141399])

array([100.        ,  86.91170874,  82.68023437])

array([86.91170874, 82.68023437])

array([100.        ,  76.21933374,  73.27201413])

array([76.21933374, 73.27201413])

array([100.        , 113.9968025 , 103.74300269])

array([113.9968025 , 103.74300269])

array([100.        ,  89.10147799,  89.43745909])

array([89.10147799, 89.43745909])

array([100.        , 112.12410529, 140.90042957])

array([112.12410529, 140.90042957])

array([100.        ,  91.39529765,  89.46869042])

array([91.39529765, 89.46869042])

array([100.        ,  69.39769284,  61.43433315])

array([69.39769284, 61.43433315])

array([100.        ,  93.64622805, 103.28043387])

array([ 93.64622805, 103.28043387])

array([100.        ,  90.77077739,  93.65147883])

array([90.77077739, 93.65147883])

array([100.        , 118.9220964 , 112.96660487])

array([118.9220964 , 112.96660487])

array([100.        ,  84.31536188, 106.88422965])

array([ 84.31536188, 106.88422965])

array([100.        ,  93.06345446, 118.42125734])

array([ 93.06345446, 118.42125734])

array([100.        ,  96.55664411, 115.9532755 ])

array([ 96.55664411, 115.9532755 ])

array([100.        , 106.32137041, 128.31893556])

array([106.32137041, 128.31893556])

array([100.        ,  76.49508467,  85.11667978])

array([76.49508467, 85.11667978])

array([100.       ,  83.2716098,  88.1640235])

array([83.2716098, 88.1640235])

array([100.        , 136.92392382, 142.73322447])

array([136.92392382, 142.73322447])

array([100.        , 122.67258515, 145.66063667])

array([122.67258515, 145.66063667])

array([100.        ,  80.92102639,  79.58692562])

array([80.92102639, 79.58692562])

array([100.        , 111.84824331,  91.33763566])

array([111.84824331,  91.33763566])

array([100.        , 128.6601394 , 164.98191537])

array([128.6601394 , 164.98191537])

array([100.        ,  84.55376549,  58.21483502])

array([84.55376549, 58.21483502])

array([100.        ,  80.5599806 ,  67.00061054])

array([80.5599806 , 67.00061054])

array([100.        ,  83.20708688, 103.07672316])

array([ 83.20708688, 103.07672316])

array([100.        ,  94.77821565,  52.68333542])

array([94.77821565, 52.68333542])

array([100.        ,  70.481103  ,  33.41425457])

array([70.481103  , 33.41425457])

array([100.        , 140.84457359, 148.01226603])

array([140.84457359, 148.01226603])

array([100.        ,  86.63218973,  91.10555201])

array([86.63218973, 91.10555201])

array([100.        ,  87.07886091,  69.30257625])

array([87.07886091, 69.30257625])

array([100.        , 166.88364342, 162.59886003])

array([166.88364342, 162.59886003])

array([100.        , 137.71308469, 174.03361934])

array([137.71308469, 174.03361934])

array([100.        , 120.12495321, 140.18751782])

array([120.12495321, 140.18751782])

array([100.        , 102.32470503, 141.15787061])

array([102.32470503, 141.15787061])

array([100.        , 143.41000221, 172.37294951])

array([143.41000221, 172.37294951])

array([100.        , 104.07901842,  93.46323287])

array([104.07901842,  93.46323287])

array([100.        ,  80.99572315,  88.98502655])

array([80.99572315, 88.98502655])

array([100.        , 136.5061344 , 120.80991824])

array([136.5061344 , 120.80991824])

array([100.        ,  88.3163723 ,  92.11716048])

array([88.3163723 , 92.11716048])

array([100.        , 105.502679  ,  97.90237392])

array([105.502679  ,  97.90237392])

array([100.        ,  86.19827843,  82.13186975])

array([86.19827843, 82.13186975])

array([100.        ,  87.13172448,  80.36846888])

array([87.13172448, 80.36846888])

array([100.        ,  94.01604881, 102.32048929])

array([ 94.01604881, 102.32048929])

array([100.        ,  72.96817555,  93.02912176])

array([72.96817555, 93.02912176])

array([100.        ,  63.80748281,  43.20097997])

array([63.80748281, 43.20097997])

array([100.        , 105.15121752,  94.70558033])

array([105.15121752,  94.70558033])

array([100.        ,  97.67148506, 103.64108454])

array([ 97.67148506, 103.64108454])

array([100.        ,  84.32321952,  75.28599017])

array([84.32321952, 75.28599017])

array([100.        ,  96.08921959, 108.52347167])

array([ 96.08921959, 108.52347167])

array([100.        , 129.55987615, 148.81889128])

array([129.55987615, 148.81889128])

array([100.        , 116.52593692, 133.81895575])

array([116.52593692, 133.81895575])

array([100.        , 102.96213672,  83.6013776 ])

array([102.96213672,  83.6013776 ])

array([100.        ,  89.4637789 ,  93.35962311])

array([89.4637789 , 93.35962311])

array([100.        , 108.36042821, 109.25975571])

array([108.36042821, 109.25975571])

array([100.        , 125.36659101, 152.46971128])

array([125.36659101, 152.46971128])

array([100.        , 123.35147739, 101.06418341])

array([123.35147739, 101.06418341])

array([100.        ,  78.86249291,  46.12806611])

array([78.86249291, 46.12806611])

array([100.        ,  88.12447549, 119.44690349])

array([ 88.12447549, 119.44690349])

array([100.        , 112.9574468 , 123.40434158])

array([112.9574468 , 123.40434158])

array([100.        ,  77.63739223,  65.55147202])

array([77.63739223, 65.55147202])

array([100.        , 140.95923074, 105.33196316])

array([140.95923074, 105.33196316])

array([100.        , 119.0419382 , 108.19541387])

array([119.0419382 , 108.19541387])

array([100.        ,  81.86457521,  55.3578013 ])

array([81.86457521, 55.3578013 ])

array([100.        , 110.68542366, 128.65203585])

array([110.68542366, 128.65203585])

array([100.        ,  67.68337088,  75.2011785 ])

array([67.68337088, 75.2011785 ])

array([100.        ,  90.58754627,  90.24824467])

array([90.58754627, 90.24824467])

array([100.        , 124.19448931, 141.20520299])

array([124.19448931, 141.20520299])

array([100.        , 108.34197557,  74.1578365 ])

array([108.34197557,  74.1578365 ])

array([100.        ,  86.43206312, 102.00848164])

array([ 86.43206312, 102.00848164])

array([100.        , 109.90762061,  43.62036544])

array([109.90762061,  43.62036544])

array([100.        , 112.27460289, 121.4674768 ])

array([112.27460289, 121.4674768 ])

array([100.        ,  55.7001328 ,  51.06407128])

array([55.7001328 , 51.06407128])

array([100.        ,  73.60904125,  85.95219378])

array([73.60904125, 85.95219378])

array([100.        ,  98.95078625,  92.81159827])

array([98.95078625, 92.81159827])

array([100.        ,  82.50663301, 137.61371369])

array([ 82.50663301, 137.61371369])

array([100.        ,  87.98408223,  63.61006189])

array([87.98408223, 63.61006189])

array([100.        ,  71.38880979,  61.22146917])

array([71.38880979, 61.22146917])

array([100.        ,  68.44974044,  66.10706717])

array([68.44974044, 66.10706717])

array([100.        , 123.02702387,  95.60782674])

array([123.02702387,  95.60782674])

array([100.        ,  77.29647134,  71.0965317 ])

array([77.29647134, 71.0965317 ])

array([100.        , 130.54956099, 142.5548212 ])

array([130.54956099, 142.5548212 ])

array([100.        , 120.65381124, 130.14449055])

array([120.65381124, 130.14449055])

array([100.        ,  98.74328809,  74.978293  ])

array([98.74328809, 74.978293  ])

array([100.        ,  85.05127303,  96.85773913])

array([85.05127303, 96.85773913])

array([100.        ,  65.47616168,  75.99916242])

array([65.47616168, 75.99916242])

array([100.        , 115.90642055,  99.03133138])

array([115.90642055,  99.03133138])

array([100.        ,  66.5504318 ,  74.47749581])

array([66.5504318 , 74.47749581])

array([100.        ,  96.12764638, 102.2240985 ])

array([ 96.12764638, 102.2240985 ])

array([100.        , 105.09297778, 130.89224923])

array([105.09297778, 130.89224923])

array([100.        , 120.92284073, 133.04916724])

array([120.92284073, 133.04916724])

array([100.        , 106.15335902,  57.71278304])

array([106.15335902,  57.71278304])

array([100.        , 101.18848161, 123.59901601])

array([101.18848161, 123.59901601])

array([100.        , 139.31635913, 150.80381971])

array([139.31635913, 150.80381971])

array([100.        , 122.47549577, 122.10924865])

array([122.47549577, 122.10924865])

array([100.        ,  67.87358625,  68.47195812])

array([67.87358625, 68.47195812])

array([100.        ,  96.95277694,  64.73083708])

array([96.95277694, 64.73083708])

array([100.        ,  76.26980298,  86.7693621 ])

array([76.26980298, 86.7693621 ])

array([100.        ,  93.92942331,  75.90922816])

array([93.92942331, 75.90922816])

array([100.        , 106.78528429, 154.20663414])

array([106.78528429, 154.20663414])

array([100.        , 127.24432071, 136.21254325])

array([127.24432071, 136.21254325])

array([100.        , 120.84596796, 116.38391235])

array([120.84596796, 116.38391235])

array([100.        , 120.73920907, 161.15568725])

array([120.73920907, 161.15568725])

array([100.        , 107.0135317 , 166.63945567])

array([107.0135317 , 166.63945567])

array([100.        ,  70.28360871,  92.09913399])

array([70.28360871, 92.09913399])

array([100.        , 109.30948772, 142.88937484])

array([109.30948772, 142.88937484])

array([100.        ,  93.05020131,  72.8929471 ])

array([93.05020131, 72.8929471 ])

array([100.        ,  83.87295047,  39.97459162])

array([83.87295047, 39.97459162])

array([100.        ,  66.11018337,  71.09542409])

array([66.11018337, 71.09542409])

array([100.        ,  68.69988328,  55.75308702])

array([68.69988328, 55.75308702])

array([100.        , 143.91571544, 154.36934116])

array([143.91571544, 154.36934116])

array([100.        ,  96.99155015, 105.55750808])

array([ 96.99155015, 105.55750808])

array([100.        , 107.58266861, 116.67969904])

array([107.58266861, 116.67969904])

array([100.        , 102.65342841,  92.17094707])

array([102.65342841,  92.17094707])

array([100.        ,  78.74721447,  91.24062756])

array([78.74721447, 91.24062756])

array([100.        ,  98.23814171,  97.07955198])

array([98.23814171, 97.07955198])

array([100.        , 138.71370017, 122.54810101])

array([138.71370017, 122.54810101])

array([100.        ,  88.9577831 , 123.95817778])

array([ 88.9577831 , 123.95817778])

array([100.        , 120.42510287, 144.28953186])

array([120.42510287, 144.28953186])

array([100.        , 148.08704804, 148.95780401])

array([148.08704804, 148.95780401])

array([100.        , 122.60558644,  81.74031537])

array([122.60558644,  81.74031537])

array([100.        ,  84.62442451, 107.18407801])

array([ 84.62442451, 107.18407801])

array([100.        ,  96.34216949, 101.36842124])

array([ 96.34216949, 101.36842124])

array([100.        ,  96.15423087,  88.5672071 ])

array([96.15423087, 88.5672071 ])

array([100.        , 157.64048527, 217.95213963])

array([157.64048527, 217.95213963])

array([100.        ,  90.26919006, 131.29352313])

array([ 90.26919006, 131.29352313])

array([100.        ,  83.76801785, 104.19671709])

array([ 83.76801785, 104.19671709])

array([100.        , 122.54019199, 131.77298512])

array([122.54019199, 131.77298512])

array([100.        , 111.64147134,  67.06101467])

array([111.64147134,  67.06101467])

array([100.        ,  77.2384884 ,  60.10556667])

array([77.2384884 , 60.10556667])

array([100.        , 103.42533408, 115.18921737])

array([103.42533408, 115.18921737])

array([100.        , 118.79227773, 138.93490102])

array([118.79227773, 138.93490102])

array([100.        ,  75.6112087 ,  51.09925413])

array([75.6112087 , 51.09925413])

array([100.        , 134.48401518, 160.00422014])

array([134.48401518, 160.00422014])

array([100.        ,  79.80127848,  59.48488996])

array([79.80127848, 59.48488996])

array([100.        , 123.38060777, 134.71504465])

array([123.38060777, 134.71504465])

array([100.        , 109.40426921, 131.51294352])

array([109.40426921, 131.51294352])

array([100.        ,  93.4716103 , 105.66167044])

array([ 93.4716103 , 105.66167044])

array([100.        , 139.39211936, 184.68212664])

array([139.39211936, 184.68212664])

array([100.        , 126.75511641, 133.20152311])

array([126.75511641, 133.20152311])

array([100.        , 109.74390426, 117.66403279])

array([109.74390426, 117.66403279])

array([100.        ,  84.51061594,  60.15374328])

array([84.51061594, 60.15374328])

array([100.        ,  96.31858909,  91.42939913])

array([96.31858909, 91.42939913])

array([100.        ,  96.43609983,  67.98074231])

array([96.43609983, 67.98074231])

array([100.        , 117.90883773,  76.37414998])

array([117.90883773,  76.37414998])

array([100.        , 116.03518632,  99.31834918])

array([116.03518632,  99.31834918])

array([100.        ,  89.59211691, 126.00361245])

array([ 89.59211691, 126.00361245])

array([100.        , 124.77985204,  86.93974651])

array([124.77985204,  86.93974651])

array([100.        , 103.21590571, 123.63927898])

array([103.21590571, 123.63927898])

array([100.        ,  85.12306096,  69.9817741 ])

array([85.12306096, 69.9817741 ])

array([100.        , 100.25502325, 107.13198238])

array([100.25502325, 107.13198238])

array([100.        , 100.26926203, 117.37547679])

array([100.26926203, 117.37547679])

array([100.        ,  69.37746532,  40.63546373])

array([69.37746532, 40.63546373])

array([100.        , 100.21356911,  69.3391864 ])

array([100.21356911,  69.3391864 ])

array([100.        ,  74.46482187,  54.10552496])

array([74.46482187, 54.10552496])

array([100.        ,  93.48486588, 129.38607846])

array([ 93.48486588, 129.38607846])

array([100.        ,  71.92553547,  75.77804957])

array([71.92553547, 75.77804957])

array([100.        ,  80.65821307,  85.62401409])

array([80.65821307, 85.62401409])

array([100.        ,  94.51280886,  90.67763403])

array([94.51280886, 90.67763403])

array([100.        , 138.00328439, 169.67929301])

array([138.00328439, 169.67929301])

array([100.        , 127.34793727, 111.44239051])

array([127.34793727, 111.44239051])

array([100.        , 112.45974116,  96.34753752])

array([112.45974116,  96.34753752])

array([100.        ,  63.38085981,  45.63407625])

array([63.38085981, 45.63407625])

array([100.        , 111.47307067, 145.9962088 ])

array([111.47307067, 145.9962088 ])

array([100.        , 117.62848395,  96.21441176])

array([117.62848395,  96.21441176])

array([100.        , 140.00614219, 122.69403377])

array([140.00614219, 122.69403377])

array([100.        , 129.20532413, 120.35996168])

array([129.20532413, 120.35996168])

array([100.        , 129.59971093, 135.99521895])

array([129.59971093, 135.99521895])

array([100.        ,  85.39043962,  59.58267412])

array([85.39043962, 59.58267412])

array([100.        , 114.57463405, 140.57234553])

array([114.57463405, 140.57234553])

array([100.        ,  64.83839823,  87.30244928])

array([64.83839823, 87.30244928])

array([100.        , 114.1579897 , 102.08653393])

array([114.1579897 , 102.08653393])

array([100.        , 108.81239737, 135.73507768])

array([108.81239737, 135.73507768])

array([100.        ,  92.67538764,  86.98034841])

array([92.67538764, 86.98034841])

array([100.        ,  89.34021132,  95.92176697])

array([89.34021132, 95.92176697])

array([100.        , 113.40841444, 108.43669014])

array([113.40841444, 108.43669014])

array([100.        , 113.64621698, 142.27112444])

array([113.64621698, 142.27112444])

array([100.        , 102.31874108,  94.81811515])

array([102.31874108,  94.81811515])

array([100.        , 113.66379226,  64.20880575])

array([113.66379226,  64.20880575])

array([100.        , 126.46969746, 136.32559832])

array([126.46969746, 136.32559832])

array([100.        ,  78.76728374,  96.09764137])

array([78.76728374, 96.09764137])

array([100.        , 133.45213217, 146.4393817 ])

array([133.45213217, 146.4393817 ])

array([100.        , 129.46332952,  77.33788165])

array([129.46332952,  77.33788165])

array([100.        , 100.13679371, 178.28504872])

array([100.13679371, 178.28504872])

array([100.        , 136.00085024, 176.12226836])

array([136.00085024, 176.12226836])

array([100.        ,  89.44237143, 112.8128615 ])

array([ 89.44237143, 112.8128615 ])

array([100.        , 142.84163102, 193.74173947])

array([142.84163102, 193.74173947])

array([100.        , 133.36199895, 148.87441314])

array([133.36199895, 148.87441314])

array([100.        , 122.00299004, 121.14590573])

array([122.00299004, 121.14590573])

array([100.        , 130.27514249,  79.74089879])

array([130.27514249,  79.74089879])

array([100.        ,  98.07499695,  73.14668587])

array([98.07499695, 73.14668587])

array([100.        ,  87.76043605,  99.81713894])

array([87.76043605, 99.81713894])

array([100.        , 130.3059857 , 165.99743244])

array([130.3059857 , 165.99743244])

array([100.        , 105.06841609, 108.1235243 ])

array([105.06841609, 108.1235243 ])

array([100.        , 109.59365274, 113.82436672])

array([109.59365274, 113.82436672])

array([100.        ,  80.20800947, 113.82114809])

array([ 80.20800947, 113.82114809])

array([100.        ,  82.14644896,  59.76197419])

array([82.14644896, 59.76197419])

array([100.        ,  73.42686042,  57.96406122])

array([73.42686042, 57.96406122])

array([100.        , 110.9225686 ,  92.89152883])

array([110.9225686 ,  92.89152883])

array([100.        , 127.62079831, 147.64108923])

array([127.62079831, 147.64108923])

array([100.        , 107.42556893, 138.52140411])

array([107.42556893, 138.52140411])

array([100.        ,  91.57726212,  80.03233054])

array([91.57726212, 80.03233054])

array([100.        ,  86.03832132,  67.34282134])

array([86.03832132, 67.34282134])

array([100.        , 111.75789374, 146.10478896])

array([111.75789374, 146.10478896])

array([100.        ,  97.45740198,  81.26741161])

array([97.45740198, 81.26741161])

array([100.        , 129.12658059, 120.44230942])

array([129.12658059, 120.44230942])

array([100.        , 130.4794009 , 145.15590741])

array([130.4794009 , 145.15590741])

array([100.        , 127.50304311, 127.49895112])

array([127.50304311, 127.49895112])

array([100.        , 104.41156941, 132.09391853])

array([104.41156941, 132.09391853])

array([100.        ,  86.1798663 , 105.41709719])

array([ 86.1798663 , 105.41709719])

array([100.        ,  90.98774195,  90.68575144])

array([90.98774195, 90.68575144])

array([100.        ,  64.84719067,  93.10095889])

array([64.84719067, 93.10095889])

array([100.        , 132.91072971,  91.83889236])

array([132.91072971,  91.83889236])

array([100.        , 113.34092036,  22.40073262])

array([113.34092036,  22.40073262])

array([100.        , 146.59052647, 181.52042458])

array([146.59052647, 181.52042458])

array([100.        , 116.08813291, 137.46213615])

array([116.08813291, 137.46213615])

array([100.        ,  78.49887172,  45.75810167])

array([78.49887172, 45.75810167])

array([100.        ,  53.9074526 ,  52.99985907])

array([53.9074526 , 52.99985907])

array([100.        ,  95.08188471,  83.06635298])

array([95.08188471, 83.06635298])

array([100.        , 101.30351725,  89.9686962 ])

array([101.30351725,  89.9686962 ])

array([100.        ,  83.50729765,  77.19538433])

array([83.50729765, 77.19538433])

array([100.        , 116.705051  , 119.40571787])

array([116.705051  , 119.40571787])

array([100.        , 115.68653404,  87.22780797])

array([115.68653404,  87.22780797])

array([100.        ,  85.2264064 ,  98.97689803])

array([85.2264064 , 98.97689803])

array([100.        , 143.06392343, 144.06679946])

array([143.06392343, 144.06679946])

array([100.        , 107.70266116, 135.10358718])

array([107.70266116, 135.10358718])

array([100.        , 118.20904476, 106.20741154])

array([118.20904476, 106.20741154])

array([100.        ,  75.35437764,  80.90430931])

array([75.35437764, 80.90430931])

array([100.        ,  98.20877364, 103.84663651])

array([ 98.20877364, 103.84663651])

array([100.        , 100.44968372,  86.46378162])

array([100.44968372,  86.46378162])

array([100.        ,  96.06740087,  77.0183896 ])

array([96.06740087, 77.0183896 ])

array([100.        , 130.62410267, 130.26188475])

array([130.62410267, 130.26188475])

array([100.        ,  82.73754707,  79.30468042])

array([82.73754707, 79.30468042])

array([100.        ,  96.27317776,  90.070489  ])

array([96.27317776, 90.070489  ])

array([100.        ,  85.02282038,  90.17046435])

array([85.02282038, 90.17046435])

array([100.        , 152.64882593, 132.11985585])

array([152.64882593, 132.11985585])

array([100.        ,  94.52242262,  85.01891811])

array([94.52242262, 85.01891811])

array([100.        ,  89.05607002, 102.72133451])

array([ 89.05607002, 102.72133451])

array([100.        , 100.51152799, 127.55407552])

array([100.51152799, 127.55407552])

array([100.        ,  87.94936166,  82.08309572])

array([87.94936166, 82.08309572])

array([100.        ,  96.74140494,  95.59880391])

array([96.74140494, 95.59880391])

array([100.        , 114.07435607,  95.68785202])

array([114.07435607,  95.68785202])

array([100.        , 109.67594607,  79.19088789])

array([109.67594607,  79.19088789])

array([100.        , 104.4514257 ,  79.55456152])

array([104.4514257 ,  79.55456152])

array([100.        , 133.70617415, 141.88416815])

array([133.70617415, 141.88416815])

array([100.        ,  86.47893738,  81.49112641])

array([86.47893738, 81.49112641])

array([100.        , 114.92856655,  78.51382466])

array([114.92856655,  78.51382466])

array([100.        ,  98.83697648, 148.92663489])

array([ 98.83697648, 148.92663489])

array([100.        ,  90.49899055,  98.58930093])

array([90.49899055, 98.58930093])

array([100.        , 113.09891295, 133.19764924])

array([113.09891295, 133.19764924])

array([100.        , 102.90334731, 102.84783648])

array([102.90334731, 102.84783648])

array([100.        , 152.91794576, 187.83535063])

array([152.91794576, 187.83535063])

array([100.        ,  70.05215445,  85.98447463])

array([70.05215445, 85.98447463])

array([100.        , 136.37618285, 175.86550099])

array([136.37618285, 175.86550099])

array([100.        ,  90.80248562,  81.2984522 ])

array([90.80248562, 81.2984522 ])

array([100.        ,  85.11116077, 115.09839789])

array([ 85.11116077, 115.09839789])

array([100.        ,  87.78418   , 106.14271853])

array([ 87.78418   , 106.14271853])

array([100.        , 107.54709415, 139.44357649])

array([107.54709415, 139.44357649])

array([100.        ,  83.36918515,  72.06980667])

array([83.36918515, 72.06980667])

array([100.        , 119.75245201,  89.10116437])

array([119.75245201,  89.10116437])

array([100.        , 102.79324734, 100.42777452])

array([102.79324734, 100.42777452])

array([100.        ,  56.33357286,  56.30032707])

array([56.33357286, 56.30032707])

array([100.        ,  90.52545431,  77.40866149])

array([90.52545431, 77.40866149])

array([100.        , 119.11521345, 146.85648473])

array([119.11521345, 146.85648473])

array([100.        , 107.12977068, 129.88401875])

array([107.12977068, 129.88401875])

array([100.        , 123.94105397,  91.07913315])

array([123.94105397,  91.07913315])

array([100.        ,  96.5485102 , 116.35900909])

array([ 96.5485102 , 116.35900909])

array([100.        ,  90.54008858,  70.38276264])

array([90.54008858, 70.38276264])

array([100.        , 123.71301283, 102.17541134])

array([123.71301283, 102.17541134])

array([100.        , 128.47497332, 135.2454061 ])

array([128.47497332, 135.2454061 ])

array([100.        , 134.37460722,  90.1990942 ])

array([134.37460722,  90.1990942 ])

array([100.        , 100.55369685,  95.09087447])

array([100.55369685,  95.09087447])

array([100.        ,  52.91012524,  59.89434835])

array([52.91012524, 59.89434835])

array([100.        , 105.62665103,  81.97386825])

array([105.62665103,  81.97386825])

array([100.        ,  72.11172314,  50.52306324])

array([72.11172314, 50.52306324])

array([100.        ,  84.3059481 ,  64.12918612])

array([84.3059481 , 64.12918612])

array([100.        ,  77.18383273,  64.14991547])

array([77.18383273, 64.14991547])

array([100.        ,  94.22914661,  97.49200402])

array([94.22914661, 97.49200402])

array([100.        , 101.94375459, 101.07167228])

array([101.94375459, 101.07167228])

array([100.        , 119.99770584, 131.80703723])

array([119.99770584, 131.80703723])

array([100.        ,  74.88353867, 108.79124748])

array([ 74.88353867, 108.79124748])

array([100.        ,  97.37636689, 134.30742252])

array([ 97.37636689, 134.30742252])

array([100.        ,  86.15229743,  71.43940698])

array([86.15229743, 71.43940698])

array([100.        ,  58.33751829,  36.50143627])

array([58.33751829, 36.50143627])

array([100.        , 128.0505863 , 118.74013936])

array([128.0505863 , 118.74013936])

array([100.        ,  86.11378484,  62.49946166])

array([86.11378484, 62.49946166])

array([100.        , 110.07463965, 125.6321808 ])

array([110.07463965, 125.6321808 ])

array([100.        ,  93.84102818,  96.67272024])

array([93.84102818, 96.67272024])

array([100.        ,  97.07659978, 122.59844248])

array([ 97.07659978, 122.59844248])

array([100.        ,  80.56828434,  94.90045952])

array([80.56828434, 94.90045952])

array([100.        ,  93.70795595,  79.92494281])

array([93.70795595, 79.92494281])

array([100.        , 103.8733347 , 129.46506031])

array([103.8733347 , 129.46506031])

array([100.        ,  99.30362722, 108.57810599])

array([ 99.30362722, 108.57810599])

array([100.        , 105.57397204, 105.40701075])

array([105.57397204, 105.40701075])

array([100.        , 119.37965941, 103.98580281])

array([119.37965941, 103.98580281])

array([100.        ,  94.47443996, 132.7010035 ])

array([ 94.47443996, 132.7010035 ])

array([100.        , 135.68010634,  96.99412231])

array([135.68010634,  96.99412231])

array([100.        , 112.92341479, 137.22862844])

array([112.92341479, 137.22862844])

array([100.        , 120.59261473, 142.44771369])

array([120.59261473, 142.44771369])

array([100.        , 133.91585521, 150.22804355])

array([133.91585521, 150.22804355])

array([100.        ,  88.72281429, 111.2126401 ])

array([ 88.72281429, 111.2126401 ])

array([100.        , 135.85353107, 134.84012062])

array([135.85353107, 134.84012062])

array([100.        , 112.77096372, 137.95524655])

array([112.77096372, 137.95524655])

array([100.        , 105.99378756,  76.20061518])

array([105.99378756,  76.20061518])

array([100.        , 107.25918733, 138.03358583])

array([107.25918733, 138.03358583])

array([100.        , 104.91716582,  96.37405891])

array([104.91716582,  96.37405891])

array([100.        , 145.73145351, 137.40745581])

array([145.73145351, 137.40745581])

array([100.        ,  83.44224812,  95.0589405 ])

array([83.44224812, 95.0589405 ])

array([100.        , 118.06618086, 116.72752115])

array([118.06618086, 116.72752115])

array([100.        , 122.26913133, 109.99288402])

array([122.26913133, 109.99288402])

array([100.        , 127.18076036, 135.6422288 ])

array([127.18076036, 135.6422288 ])

array([100.        , 109.8686574 ,  54.00479444])

array([109.8686574 ,  54.00479444])

array([100.        ,  95.443618  ,  96.88038014])

array([95.443618  , 96.88038014])

array([100.        , 134.16483622, 136.81416988])

array([134.16483622, 136.81416988])

array([100.        , 117.84604069, 107.25258192])

array([117.84604069, 107.25258192])

array([100.        ,  52.59626911,  51.21543756])

array([52.59626911, 51.21543756])

array([100.        ,  98.39250023,  58.07457784])

array([98.39250023, 58.07457784])

array([100.        , 111.73734054, 156.33480358])

array([111.73734054, 156.33480358])

array([100.        , 120.66066843, 104.90474194])

array([120.66066843, 104.90474194])

array([100.        , 109.50809263, 120.70983004])

array([109.50809263, 120.70983004])

array([100.        ,  90.11931558,  88.0310667 ])

array([90.11931558, 88.0310667 ])

array([100.        ,  89.01611368,  81.25688544])

array([89.01611368, 81.25688544])

array([100.        ,  74.97833839,  88.09292026])

array([74.97833839, 88.09292026])

array([100.        , 102.82073169,  93.9005653 ])

array([102.82073169,  93.9005653 ])

array([100.        ,  74.75435066,  87.41555796])

array([74.75435066, 87.41555796])

array([100.        ,  95.17330746,  76.87475726])

array([95.17330746, 76.87475726])

array([100.        ,  93.673904  ,  93.57904182])

array([93.673904  , 93.57904182])

array([100.        ,  96.5346348 ,  99.84204491])

array([96.5346348 , 99.84204491])

array([100.        ,  83.70340186,  85.57002956])

array([83.70340186, 85.57002956])

array([100.        ,  66.86092292,  47.98576903])

array([66.86092292, 47.98576903])

array([100.        , 100.64399846,  76.27849128])

array([100.64399846,  76.27849128])

array([100.        , 117.05980051, 119.56518726])

array([117.05980051, 119.56518726])

array([100.        , 107.83109467, 115.05397989])

array([107.83109467, 115.05397989])

array([100.        , 115.66802474, 122.92471426])

array([115.66802474, 122.92471426])

array([100.        ,  92.86329933,  62.88623712])

array([92.86329933, 62.88623712])

array([100.        , 116.63309856, 103.80594107])

array([116.63309856, 103.80594107])

array([100.        , 111.95363489, 129.35144275])

array([111.95363489, 129.35144275])

array([100.        ,  73.42125405,  67.80823132])

array([73.42125405, 67.80823132])

array([100.        , 100.2420148 , 105.13167738])

array([100.2420148 , 105.13167738])

array([100.        ,  71.19307403,  88.05702228])

array([71.19307403, 88.05702228])

array([100.        , 110.50491501, 141.83674846])

array([110.50491501, 141.83674846])

array([100.        ,  74.64087746,  86.91425286])

array([74.64087746, 86.91425286])

array([100.        , 112.85237452, 140.06095621])

array([112.85237452, 140.06095621])

array([100.        , 126.59107992, 113.66921329])

array([126.59107992, 113.66921329])

array([100.        ,  84.31341242,  89.15524028])

array([84.31341242, 89.15524028])

array([100.        , 107.20752536,  99.35732627])

array([107.20752536,  99.35732627])

array([100.        , 117.90208166,  80.97969095])

array([117.90208166,  80.97969095])

array([100.        , 110.95904957, 135.57524602])

array([110.95904957, 135.57524602])

array([100.        ,  92.6546861 ,  80.72473981])

array([92.6546861 , 80.72473981])

array([100.        , 143.0109415 , 155.67029933])

array([143.0109415 , 155.67029933])

array([100.        ,  64.09570571,  77.2641232 ])

array([64.09570571, 77.2641232 ])

array([100.        ,  95.80989135, 113.64367704])

array([ 95.80989135, 113.64367704])

array([100.        , 131.75986717, 139.85041618])

array([131.75986717, 139.85041618])

array([100.        ,  95.25409736, 128.00645149])

array([ 95.25409736, 128.00645149])

array([100.        ,  70.81662982,  73.30174255])

array([70.81662982, 73.30174255])

array([100.        , 119.63386999, 167.02375808])

array([119.63386999, 167.02375808])

array([100.        , 100.00846745, 123.46727177])

array([100.00846745, 123.46727177])

array([100.        ,  96.29572381, 103.79748143])

array([ 96.29572381, 103.79748143])

array([100.        ,  99.2016645 , 138.36911831])

array([ 99.2016645 , 138.36911831])

array([100.        ,  83.18018536,  76.29389629])

array([83.18018536, 76.29389629])

array([100.        , 107.64760336, 136.13721343])

array([107.64760336, 136.13721343])

array([100.        , 116.27512635, 142.13614658])

array([116.27512635, 142.13614658])

array([100.        ,  99.97683442, 112.27167315])

array([ 99.97683442, 112.27167315])

array([100.        ,  81.41574277,  93.1363783 ])

array([81.41574277, 93.1363783 ])

array([100.        , 139.11952373, 132.10059631])

array([139.11952373, 132.10059631])

array([100.        , 142.8926624 , 153.01549331])

array([142.8926624 , 153.01549331])

array([100.        , 129.74766207,  54.77972072])

array([129.74766207,  54.77972072])

array([100.        , 107.24135481, 102.91067067])

array([107.24135481, 102.91067067])

array([100.        ,  72.75049623,  70.92577519])

array([72.75049623, 70.92577519])

array([100.        , 102.81050796,  65.03495251])

array([102.81050796,  65.03495251])

array([100.        , 113.41327427,  94.94127853])

array([113.41327427,  94.94127853])

array([100.        ,  97.56245362,  82.69479288])

array([97.56245362, 82.69479288])

array([100.        ,  79.04814936, 111.94812542])

array([ 79.04814936, 111.94812542])

array([100.        , 101.34134417,  96.22617377])

array([101.34134417,  96.22617377])

array([100.        , 118.90717547, 101.31425655])

array([118.90717547, 101.31425655])

array([100.        ,  95.94479092,  80.0445677 ])

array([95.94479092, 80.0445677 ])

array([100.        , 114.90740209, 109.73567729])

array([114.90740209, 109.73567729])

array([100.        , 110.89805212, 110.7488034 ])

array([110.89805212, 110.7488034 ])

array([100.        , 148.75382546, 170.16713308])

array([148.75382546, 170.16713308])

array([100.        , 116.55573305, 112.67307998])

array([116.55573305, 112.67307998])

array([100.        ,  89.35876573,  86.02617221])

array([89.35876573, 86.02617221])

array([100.        , 113.38485042, 135.80263389])

array([113.38485042, 135.80263389])

array([100.        , 117.07806516, 115.27782923])

array([117.07806516, 115.27782923])

array([100.        ,  46.52971943,  57.09030352])

array([46.52971943, 57.09030352])

array([100.        ,  99.39871717,  83.44394453])

array([99.39871717, 83.44394453])

array([100.        , 106.05363649,  82.37154214])

array([106.05363649,  82.37154214])

array([100.        , 118.22999681, 153.05298074])

array([118.22999681, 153.05298074])

array([100.        ,  56.74335925,  69.43099056])

array([56.74335925, 69.43099056])

array([100.        , 122.28047389, 108.97374181])

array([122.28047389, 108.97374181])

array([100.        ,  74.98592876,  52.88231515])

array([74.98592876, 52.88231515])

array([100.        , 141.32791677, 134.44456087])

array([141.32791677, 134.44456087])

array([100.        ,  97.66117763, 116.94967722])

array([ 97.66117763, 116.94967722])

array([100.        ,  76.91978145,  46.94266602])

array([76.91978145, 46.94266602])

array([100.        , 102.38541318, 101.90027363])

array([102.38541318, 101.90027363])

array([100.        , 107.68850456, 127.97362776])

array([107.68850456, 127.97362776])

array([100.        , 133.54956765, 184.302416  ])

array([133.54956765, 184.302416  ])

array([100.        , 112.43614118, 103.55748863])

array([112.43614118, 103.55748863])

array([100.        , 126.08809645,  99.22639135])

array([126.08809645,  99.22639135])

array([100.        , 126.64710294, 111.07670002])

array([126.64710294, 111.07670002])

array([100.        ,  80.1681666 ,  93.41168825])

array([80.1681666 , 93.41168825])

array([100.        , 127.54830657, 100.600331  ])

array([127.54830657, 100.600331  ])

array([100.        , 127.2000144 ,  87.73832348])

array([127.2000144 ,  87.73832348])

array([100.        ,  89.33760206, 105.48669376])

array([ 89.33760206, 105.48669376])

array([100.        ,  97.98512608,  94.73253057])

array([97.98512608, 94.73253057])

array([100.        , 119.32594281, 114.13067919])

array([119.32594281, 114.13067919])

array([100.        ,  72.88894509,  70.34134801])

array([72.88894509, 70.34134801])

array([100.        ,  46.80440516,  34.038699  ])

array([46.80440516, 34.038699  ])

array([100.        , 114.55452073, 139.5593717 ])

array([114.55452073, 139.5593717 ])

array([100.        , 106.26164397,  92.16865579])

array([106.26164397,  92.16865579])

array([100.        , 108.13291681,  95.51742424])

array([108.13291681,  95.51742424])

array([100.        , 112.76837131, 111.48728041])

array([112.76837131, 111.48728041])

array([100.        , 129.97648035, 158.26460376])

array([129.97648035, 158.26460376])

array([100.        , 120.20869776,  92.1247427 ])

array([120.20869776,  92.1247427 ])

array([100.        ,  98.95120561, 157.83979751])

array([ 98.95120561, 157.83979751])

array([100.        , 114.35412256, 130.40408193])

array([114.35412256, 130.40408193])

array([100.        , 123.62239338,  60.52362723])

array([123.62239338,  60.52362723])

array([100.        ,  79.71070675,  72.64809249])

array([79.71070675, 72.64809249])

array([100.        ,  74.62453334,  77.08871553])

array([74.62453334, 77.08871553])

array([100.        , 122.10979205, 128.87270076])

array([122.10979205, 128.87270076])

array([100.        , 103.21109589, 103.67351626])

array([103.21109589, 103.67351626])

array([100.        , 129.34114795, 122.09814356])

array([129.34114795, 122.09814356])

array([100.        , 115.71292385, 108.13887909])

array([115.71292385, 108.13887909])

array([100.        ,  80.94690714,  66.70570321])

array([80.94690714, 66.70570321])

array([100.        ,  88.98310615,  72.11856864])

array([88.98310615, 72.11856864])

array([100.        , 107.95652061, 123.06514022])

array([107.95652061, 123.06514022])

array([100.        , 105.91084033, 140.11475686])

array([105.91084033, 140.11475686])

array([100.        , 107.61673662, 128.55542275])

array([107.61673662, 128.55542275])

array([100.        ,  72.91692705,  73.16288304])

array([72.91692705, 73.16288304])

array([100.        , 111.67700231, 152.81670196])

array([111.67700231, 152.81670196])

array([100.        ,  85.75540239,  78.1352623 ])

array([85.75540239, 78.1352623 ])

array([100.        , 152.86486402, 145.84526626])

array([152.86486402, 145.84526626])

array([100.        ,  72.28637462,  54.22323251])

array([72.28637462, 54.22323251])

array([100.        ,  94.66360636, 127.55169801])

array([ 94.66360636, 127.55169801])

array([100.        ,  92.42784714, 123.94035598])

array([ 92.42784714, 123.94035598])

array([100.        ,  95.2922442 , 128.25279002])

array([ 95.2922442 , 128.25279002])

array([100.        , 114.82788034, 105.58195361])

array([114.82788034, 105.58195361])

array([100.        , 131.15452514, 133.9353613 ])

array([131.15452514, 133.9353613 ])

array([100.        ,  84.79814444,  81.19923332])

array([84.79814444, 81.19923332])

array([100.        ,  94.75209859, 113.39763248])

array([ 94.75209859, 113.39763248])

array([100.        , 118.13821162, 175.483914  ])

array([118.13821162, 175.483914  ])

array([100.        ,  81.6392293 ,  75.72829074])

array([81.6392293 , 75.72829074])

array([100.        ,  88.67888141,  87.04366925])

array([88.67888141, 87.04366925])

array([100.        , 117.06917524, 155.64869037])

array([117.06917524, 155.64869037])

array([100.        ,  85.75442191,  81.21393021])

array([85.75442191, 81.21393021])

array([100.        , 113.19938575, 122.80360355])

array([113.19938575, 122.80360355])

array([100.        , 122.58453608, 130.6143607 ])

array([122.58453608, 130.6143607 ])

array([100.        , 138.33483898, 144.3032083 ])

array([138.33483898, 144.3032083 ])

array([100.        , 143.13449319, 136.07201408])

array([143.13449319, 136.07201408])

array([100.        , 140.74980057, 101.21719622])

array([140.74980057, 101.21719622])

array([100.        , 141.65281384, 134.55488629])

array([141.65281384, 134.55488629])

array([100.        , 109.89072118,  88.19253098])

array([109.89072118,  88.19253098])

array([100.        ,  87.2141184 ,  83.47966923])

array([87.2141184 , 83.47966923])

array([100.        , 130.37740635, 158.79766598])

array([130.37740635, 158.79766598])

array([100.        , 103.89872828, 121.83970624])

array([103.89872828, 121.83970624])

array([100.        ,  83.27134831, 129.2242925 ])

array([ 83.27134831, 129.2242925 ])

array([100.        ,  81.35573431,  69.94148807])

array([81.35573431, 69.94148807])

array([100.        ,  95.40366483, 127.49797936])

array([ 95.40366483, 127.49797936])

array([100.        , 104.39309044, 127.53812456])

array([104.39309044, 127.53812456])

array([100.        , 115.59826905, 104.71632378])

array([115.59826905, 104.71632378])

array([100.        ,  88.32633201,  80.95569634])

array([88.32633201, 80.95569634])

array([100.        , 101.71138564,  75.67100319])

array([101.71138564,  75.67100319])

array([100.        , 129.16914192, 141.71936255])

array([129.16914192, 141.71936255])

array([100.        ,  85.91227109,  73.79071226])

array([85.91227109, 73.79071226])

array([100.        , 112.53064232, 100.1231899 ])

array([112.53064232, 100.1231899 ])

array([100.        ,  83.7744726 ,  76.17828824])

array([83.7744726 , 76.17828824])

array([100.        , 128.27344063, 160.62352066])

array([128.27344063, 160.62352066])

array([100.        ,  87.82818932,  84.19769838])

array([87.82818932, 84.19769838])

array([100.        ,  95.42593426,  91.69519346])

array([95.42593426, 91.69519346])

array([100.        , 102.18208964,  99.70332653])

array([102.18208964,  99.70332653])

array([100.        , 123.44426302, 129.16505035])

array([123.44426302, 129.16505035])

array([100.        , 114.90114459, 114.43584178])

array([114.90114459, 114.43584178])

array([100.        ,  89.45263775,  90.19662135])

array([89.45263775, 90.19662135])

array([100.        , 150.503938  , 140.56540661])

array([150.503938  , 140.56540661])

array([100.        , 118.89994912,  88.5762408 ])

array([118.89994912,  88.5762408 ])

array([100.        ,  84.912621  ,  88.41506025])

array([84.912621  , 88.41506025])

array([100.        , 113.41712024, 113.01030375])

array([113.41712024, 113.01030375])

array([100.        ,  84.88981668,  77.34838143])

array([84.88981668, 77.34838143])

array([100.       , 120.115105 , 125.9224235])

array([120.115105 , 125.9224235])

array([100.        , 105.25482821, 131.29037837])

array([105.25482821, 131.29037837])

array([100.        ,  94.38500185,  99.07752089])

array([94.38500185, 99.07752089])

array([100.        ,  57.43269142,  45.40707055])

array([57.43269142, 45.40707055])

array([100.        , 109.49632742,  95.72136397])

array([109.49632742,  95.72136397])

array([100.        ,  80.97151849, 103.7464034 ])

array([ 80.97151849, 103.7464034 ])

array([100.        ,  82.43322342, 101.57416261])

array([ 82.43322342, 101.57416261])

array([100.        ,  65.82861594,  74.67056359])

array([65.82861594, 74.67056359])

array([100.        ,  76.39075603,  85.73291645])

array([76.39075603, 85.73291645])

array([100.        ,  93.64229275,  51.50592191])

array([93.64229275, 51.50592191])

array([100.        ,  94.9599446 ,  96.86497992])

array([94.9599446 , 96.86497992])

array([100.        , 101.74301064,  97.66851293])

array([101.74301064,  97.66851293])

array([100.        , 118.67295706,  88.98766665])

array([118.67295706,  88.98766665])

array([100.        , 109.57000033,  88.92525098])

array([109.57000033,  88.92525098])

array([100.        ,  64.08250389,  87.19522311])

array([64.08250389, 87.19522311])

array([100.        , 105.69663053,  70.89311166])

array([105.69663053,  70.89311166])

array([100.        ,  98.78137335, 107.79013259])

array([ 98.78137335, 107.79013259])

array([100.        ,  63.26352841,  83.14720056])

array([63.26352841, 83.14720056])

array([100.        ,  96.38841439,  68.50417638])

array([96.38841439, 68.50417638])

array([100.        ,  99.05709185,  72.24363224])

array([99.05709185, 72.24363224])

array([100.        ,  90.89757371,  98.95570692])

array([90.89757371, 98.95570692])

array([100.        , 136.63116552, 168.30079178])

array([136.63116552, 168.30079178])

array([100.        ,  70.79055091,  72.28278868])

array([70.79055091, 72.28278868])

array([100.        , 136.36112381, 177.95158961])

array([136.36112381, 177.95158961])

array([100.        , 102.40990203, 118.99396674])

array([102.40990203, 118.99396674])

array([100.        ,  91.56859665, 118.5852715 ])

array([ 91.56859665, 118.5852715 ])

array([100.        ,  92.20882903, 110.20896208])

array([ 92.20882903, 110.20896208])

array([100.        ,  65.56227216,  69.34529702])

array([65.56227216, 69.34529702])

array([100.        , 131.03066076, 136.03608223])

array([131.03066076, 136.03608223])

array([100.        , 134.22145894, 121.63296102])

array([134.22145894, 121.63296102])

array([100.        ,  99.8001941 , 114.62940292])

array([ 99.8001941 , 114.62940292])

array([100.        , 116.26466968,  94.68215354])

array([116.26466968,  94.68215354])

array([100.        ,  31.56161934,  34.59331337])

array([31.56161934, 34.59331337])

array([100.        , 133.99768217, 151.73172805])

array([133.99768217, 151.73172805])

array([100.        , 116.29033049, 136.29902487])

array([116.29033049, 136.29902487])

array([100.        ,  62.34761224,  66.79873149])

array([62.34761224, 66.79873149])

array([100.        ,  99.75074548, 129.31217552])

array([ 99.75074548, 129.31217552])

array([100.        ,  90.03387523,  93.57449687])

array([90.03387523, 93.57449687])

array([100.        , 138.36597402, 178.80682763])

array([138.36597402, 178.80682763])

array([100.        ,  72.72803495,  72.29524903])

array([72.72803495, 72.29524903])

array([100.        ,  98.28610577, 120.42307342])

array([ 98.28610577, 120.42307342])

array([100.        ,  86.38491633,  70.18906549])

array([86.38491633, 70.18906549])

array([100.        , 120.3626941 ,  99.25952338])

array([120.3626941 ,  99.25952338])

array([100.        ,  93.68810682, 105.81009167])

array([ 93.68810682, 105.81009167])

array([100.        ,  78.11761581,  79.35752073])

array([78.11761581, 79.35752073])

array([100.        , 117.63638191, 105.0939988 ])

array([117.63638191, 105.0939988 ])

array([100.        , 103.13595426,  65.0410725 ])

array([103.13595426,  65.0410725 ])

array([100.        , 119.19169589,  79.07614893])

array([119.19169589,  79.07614893])

array([100.        ,  93.79521386, 104.46863075])

array([ 93.79521386, 104.46863075])

array([100.        ,  99.33375161,  94.47439634])

array([99.33375161, 94.47439634])

array([100.        , 100.13960708, 106.89054381])

array([100.13960708, 106.89054381])

array([100.        ,  99.62408274, 110.39678964])

array([ 99.62408274, 110.39678964])

array([100.        ,  47.32820994,  55.26617745])

array([47.32820994, 55.26617745])

array([100.        , 127.39742273, 101.20674033])

array([127.39742273, 101.20674033])

array([100.        , 132.80956386, 135.40322327])

array([132.80956386, 135.40322327])

array([100.        , 108.63251873, 140.19772398])

array([108.63251873, 140.19772398])

array([100.        , 107.61148948,  74.82230679])

array([107.61148948,  74.82230679])

array([100.        , 112.14058379, 104.61035016])

array([112.14058379, 104.61035016])

array([100.        ,  79.45097383,  94.93376301])

array([79.45097383, 94.93376301])

array([100.        ,  78.16488834,  79.99990687])

array([78.16488834, 79.99990687])

array([100.        ,  89.96356439, 103.78824809])

array([ 89.96356439, 103.78824809])

array([100.        , 104.02605521,  91.88738747])

array([104.02605521,  91.88738747])

array([100.        , 118.49384179, 112.37436626])

array([118.49384179, 112.37436626])

array([100.        , 102.32609204, 116.24834241])

array([102.32609204, 116.24834241])

array([100.        , 137.71126271,  91.76183695])

array([137.71126271,  91.76183695])

array([100.        , 123.63730802, 108.48705687])

array([123.63730802, 108.48705687])

array([100.        , 121.95523942, 110.16561734])

array([121.95523942, 110.16561734])

array([100.        ,  90.94671317,  98.99399088])

array([90.94671317, 98.99399088])

array([100.        ,  97.38263936,  82.61428602])

array([97.38263936, 82.61428602])

array([100.        , 115.27099832, 109.53693085])

array([115.27099832, 109.53693085])

array([100.        , 125.09554417, 146.94241246])

array([125.09554417, 146.94241246])

array([100.        , 156.58388778, 123.55661741])

array([156.58388778, 123.55661741])

array([100.        ,  90.51556542,  91.24304917])

array([90.51556542, 91.24304917])

array([100.        , 107.32655815,  93.11277939])

array([107.32655815,  93.11277939])

array([100.        ,  79.7239162 ,  84.88741678])

array([79.7239162 , 84.88741678])

array([100.        ,  79.99944713,  74.34133263])

array([79.99944713, 74.34133263])

array([100.        ,  77.94068762,  90.43104065])

array([77.94068762, 90.43104065])

array([100.        , 123.696519  , 140.05625345])

array([123.696519  , 140.05625345])

array([100.        , 102.42771434,  78.94721806])

array([102.42771434,  78.94721806])

array([100.        ,  85.2866603 , 134.34991302])

array([ 85.2866603 , 134.34991302])

array([100.        , 130.98569477, 100.31810523])

array([130.98569477, 100.31810523])

array([100.        , 123.11901263, 129.41523543])

array([123.11901263, 129.41523543])

array([100.        ,  88.43784045,  80.13762882])

array([88.43784045, 80.13762882])

array([100.        ,  73.99235831,  74.35468868])

array([73.99235831, 74.35468868])

array([100.        ,  97.17347945,  99.46723596])

array([97.17347945, 99.46723596])

array([100.        ,  81.78456018,  79.53136051])

array([81.78456018, 79.53136051])

array([100.        , 106.74104517, 124.11266596])

array([106.74104517, 124.11266596])

array([100.        ,  88.59937952,  81.38028238])

array([88.59937952, 81.38028238])

array([100.        ,  97.47937219, 109.89790365])

array([ 97.47937219, 109.89790365])

array([100.        ,  76.82947819,  92.87032665])

array([76.82947819, 92.87032665])

array([100.        , 113.33617798,  98.91450493])

array([113.33617798,  98.91450493])

array([100.        ,  76.13835345,  64.99564876])

array([76.13835345, 64.99564876])

array([100.        ,  90.60720627, 121.8967312 ])

array([ 90.60720627, 121.8967312 ])

array([100.        ,  99.74142174, 147.20320833])

array([ 99.74142174, 147.20320833])

array([100.        , 120.58772131,  81.57654223])

array([120.58772131,  81.57654223])

array([100.        ,  74.34423061,  76.2545503 ])

array([74.34423061, 76.2545503 ])

array([100.        , 138.93750753, 154.8898942 ])

array([138.93750753, 154.8898942 ])

array([100.        , 142.56198309, 126.4263248 ])

array([142.56198309, 126.4263248 ])

array([100.        , 108.6701809 ,  99.82353191])

array([108.6701809 ,  99.82353191])

array([100.        , 100.40663631,  93.89189967])

array([100.40663631,  93.89189967])

array([100.        , 102.67581968, 123.00181314])

array([102.67581968, 123.00181314])

array([100.        , 113.08695093, 102.15738904])

array([113.08695093, 102.15738904])

array([100.        , 133.82250376, 168.10007444])

array([133.82250376, 168.10007444])

array([100.        , 109.45343098, 116.82781463])

array([109.45343098, 116.82781463])

array([100.        ,  63.00009188,  60.18937892])

array([63.00009188, 60.18937892])

array([100.        ,  98.62367281, 100.66115256])

array([ 98.62367281, 100.66115256])

array([100.        , 123.35207933, 185.31922482])

array([123.35207933, 185.31922482])

array([100.        , 152.69436673, 102.44028175])

array([152.69436673, 102.44028175])

array([100.        ,  99.4527628 ,  87.50764356])

array([99.4527628 , 87.50764356])

array([100.        ,  68.07016229,  59.87746214])

array([68.07016229, 59.87746214])

array([100.        , 111.09171605,  91.15002719])

array([111.09171605,  91.15002719])

array([100.        ,  57.3392708 ,  46.82043601])

array([57.3392708 , 46.82043601])

array([100.        ,  85.13340087,  67.41394989])

array([85.13340087, 67.41394989])

array([100.        ,  64.32019557,  65.65066603])

array([64.32019557, 65.65066603])

array([100.        , 107.02184431, 106.94223339])

array([107.02184431, 106.94223339])

array([100.       ,  69.4944823,  57.17703  ])

array([69.4944823, 57.17703  ])

array([100.        ,  87.36998314,  64.39577761])

array([87.36998314, 64.39577761])

array([100.        , 117.92798136, 164.1480849 ])

array([117.92798136, 164.1480849 ])

array([100.        ,  58.6237253 ,  41.00378391])

array([58.6237253 , 41.00378391])

array([100.        ,  97.00402516, 106.02462824])

array([ 97.00402516, 106.02462824])

array([100.        , 101.53237759, 118.01027555])

array([101.53237759, 118.01027555])

array([100.        ,  75.08217157, 100.49742571])

array([ 75.08217157, 100.49742571])

array([100.        , 103.41560675,  92.951775  ])

array([103.41560675,  92.951775  ])

array([100.        , 131.49785601, 148.81233484])

array([131.49785601, 148.81233484])

array([100.        , 111.50172938, 115.46177121])

array([111.50172938, 115.46177121])

array([100.        , 107.52849867, 123.67257744])

array([107.52849867, 123.67257744])

array([100.        , 113.99698692,  97.6417078 ])

array([113.99698692,  97.6417078 ])

array([100.        , 104.01619467,  85.72864683])

array([104.01619467,  85.72864683])

array([100.        , 141.62984543, 173.78963655])

array([141.62984543, 173.78963655])

array([100.        ,  93.91416438, 140.82629765])

array([ 93.91416438, 140.82629765])

array([100.        ,  92.71402225,  83.85676433])

array([92.71402225, 83.85676433])

array([100.        , 124.70415166, 170.44454037])

array([124.70415166, 170.44454037])

array([100.        ,  57.81239781,  64.40401395])

array([57.81239781, 64.40401395])

array([100.        ,  66.80690149,  80.77446028])

array([66.80690149, 80.77446028])

array([100.        ,  84.44361032, 121.74579007])

array([ 84.44361032, 121.74579007])

array([100.        ,  97.51215466, 105.37584196])

array([ 97.51215466, 105.37584196])

array([100.        , 123.15965013, 141.733285  ])

array([123.15965013, 141.733285  ])

array([100.        , 111.26952025, 126.84791071])

array([111.26952025, 126.84791071])

array([100.        , 122.96081583, 182.25482184])

array([122.96081583, 182.25482184])

array([100.        , 109.92723163, 111.89117872])

array([109.92723163, 111.89117872])

array([100.        , 121.23811297, 112.1003081 ])

array([121.23811297, 112.1003081 ])

array([100.        , 109.4883817 , 120.86359617])

array([109.4883817 , 120.86359617])

array([100.        , 143.28890061, 203.21885075])

array([143.28890061, 203.21885075])

array([100.        , 106.99118969, 110.48190167])

array([106.99118969, 110.48190167])

array([100.        , 101.79687106,  73.91509714])

array([101.79687106,  73.91509714])

array([100.        ,  61.45674248,  72.16430339])

array([61.45674248, 72.16430339])

array([100.        ,  75.51957331,  85.33355806])

array([75.51957331, 85.33355806])

array([100.        , 139.74055424, 119.95118833])

array([139.74055424, 119.95118833])

array([100.        , 146.77792623, 189.09484192])

array([146.77792623, 189.09484192])

array([100.        ,  97.20971829, 125.08231629])

array([ 97.20971829, 125.08231629])

array([100.        , 102.849862  ,  92.98643411])

array([102.849862  ,  92.98643411])

array([100.        , 126.31660284, 146.90197128])

array([126.31660284, 146.90197128])

array([100.        , 100.58849718, 115.88289355])

array([100.58849718, 115.88289355])

array([100.        , 112.43176014, 128.14514031])

array([112.43176014, 128.14514031])

array([100.        ,  79.07165372,  89.23403879])

array([79.07165372, 89.23403879])

array([100.        , 107.62877781,  92.54130331])

array([107.62877781,  92.54130331])

array([100.        , 124.68007517, 141.09679284])

array([124.68007517, 141.09679284])

array([100.        , 113.75409198, 114.27452023])

array([113.75409198, 114.27452023])

array([100.        ,  85.14209004,  61.90583208])

array([85.14209004, 61.90583208])

array([100.        , 109.66450032,  94.63798341])

array([109.66450032,  94.63798341])

array([100.        , 126.35412501, 111.45322383])

array([126.35412501, 111.45322383])

array([100.        , 116.60968104, 103.60433561])

array([116.60968104, 103.60433561])

array([100.        , 149.28893169, 128.77661646])

array([149.28893169, 128.77661646])

array([100.        , 122.68687668, 124.57237799])

array([122.68687668, 124.57237799])

array([100.        ,  63.83234965,  54.55738834])

array([63.83234965, 54.55738834])

array([100.        , 124.38295608, 108.1974683 ])

array([124.38295608, 108.1974683 ])

array([100.        , 118.24121382, 153.26305052])

array([118.24121382, 153.26305052])

array([100.        , 106.42900149, 136.95008804])

array([106.42900149, 136.95008804])

array([100.        ,  98.02159906,  86.83424316])

array([98.02159906, 86.83424316])

array([100.        ,  50.79436802,  35.26139961])

array([50.79436802, 35.26139961])

array([100.        , 116.50914786, 101.08895206])

array([116.50914786, 101.08895206])

array([100.        , 150.59073043, 184.49874557])

array([150.59073043, 184.49874557])

array([100.        , 103.6627631 ,  96.45664793])

array([103.6627631 ,  96.45664793])

array([100.        , 102.76425396, 100.00388617])

array([102.76425396, 100.00388617])

array([100.        , 118.05237341, 146.04503194])

array([118.05237341, 146.04503194])

array([100.        , 102.84385139,  78.01709412])

array([102.84385139,  78.01709412])

array([100.        ,  85.06848349, 102.48741643])

array([ 85.06848349, 102.48741643])

array([100.        ,  99.44252507,  86.40986193])

array([99.44252507, 86.40986193])

array([100.        , 128.40552783, 114.49670185])

array([128.40552783, 114.49670185])

array([100.        ,  99.11365304, 131.66554674])

array([ 99.11365304, 131.66554674])

array([100.        , 100.78152488,  99.08170466])

array([100.78152488,  99.08170466])

array([100.        ,  90.13660039, 103.26135353])

array([ 90.13660039, 103.26135353])

array([100.        , 101.4928038 ,  61.10184764])

array([101.4928038 ,  61.10184764])

array([100.        , 114.68119294, 159.65689655])

array([114.68119294, 159.65689655])

array([100.        , 102.50316547, 105.70102775])

array([102.50316547, 105.70102775])

array([100.        , 110.27792879, 138.57217203])

array([110.27792879, 138.57217203])

array([100.        , 105.03365202,  96.34710831])

array([105.03365202,  96.34710831])

array([100.        ,  74.40546095,  75.50486263])

array([74.40546095, 75.50486263])

array([100.        ,  80.33616955,  96.85485064])

array([80.33616955, 96.85485064])

array([100.        , 100.71136525, 122.90119674])

array([100.71136525, 122.90119674])

array([100.        ,  87.84907274,  90.16551695])

array([87.84907274, 90.16551695])

array([100.        , 136.56523955, 141.15476636])

array([136.56523955, 141.15476636])

array([100.        , 112.86224065,  81.72887656])

array([112.86224065,  81.72887656])

array([100.        ,  92.56232953, 114.03038898])

array([ 92.56232953, 114.03038898])

array([100.       , 115.5330981, 118.8176899])

array([115.5330981, 118.8176899])

array([100.        ,  58.4507553 ,  78.78872288])

array([58.4507553 , 78.78872288])

array([100.        , 123.08487465, 151.90098951])

array([123.08487465, 151.90098951])

array([100.        ,  93.50062113,  99.31154327])

array([93.50062113, 99.31154327])

array([100.        , 114.56157669,  99.88816993])

array([114.56157669,  99.88816993])

array([100.        ,  95.59795944, 121.00105198])

array([ 95.59795944, 121.00105198])

array([100.        ,  80.72200073,  91.95302255])

array([80.72200073, 91.95302255])

array([100.        , 112.36357504,  78.059282  ])

array([112.36357504,  78.059282  ])

array([100.        ,  80.15222961,  79.56767735])

array([80.15222961, 79.56767735])

array([100.        ,  66.83298063,  49.29031861])

array([66.83298063, 49.29031861])

array([100.        ,  70.37947823,  73.94464073])

array([70.37947823, 73.94464073])

array([100.        , 104.1136945 , 125.01349083])

array([104.1136945 , 125.01349083])

array([100.        ,  69.35316991,  66.60188937])

array([69.35316991, 66.60188937])

array([100.        ,  79.17607173,  61.20199342])

array([79.17607173, 61.20199342])

array([100.        ,  94.84116413,  86.60489984])

array([94.84116413, 86.60489984])

array([100.        ,  83.05944735,  74.94853697])

array([83.05944735, 74.94853697])

array([100.        , 135.92997596, 147.8048331 ])

array([135.92997596, 147.8048331 ])

array([100.        ,  86.2438254 ,  87.70032374])

array([86.2438254 , 87.70032374])

array([100.        ,  85.93008534, 106.34298001])

array([ 85.93008534, 106.34298001])

array([100.        , 136.89451724, 104.45873218])

array([136.89451724, 104.45873218])

array([100.        ,  92.55668747, 108.52718813])

array([ 92.55668747, 108.52718813])

array([100.        , 107.18280281, 100.56765514])

array([107.18280281, 100.56765514])

array([100.        , 103.1370968 , 131.64654394])

array([103.1370968 , 131.64654394])

array([100.        ,  91.83647382, 104.55354292])

array([ 91.83647382, 104.55354292])

array([100.        ,  74.48445656, 100.62099435])

array([ 74.48445656, 100.62099435])

array([100.        ,  83.46346201, 104.71023731])

array([ 83.46346201, 104.71023731])

array([100.       ,  90.0032713,  83.9928559])

array([90.0032713, 83.9928559])

array([100.        ,  96.44082806,  81.40334163])

array([96.44082806, 81.40334163])

array([100.        ,  87.42103248, 105.43691702])

array([ 87.42103248, 105.43691702])

array([100.        , 111.18746422, 102.01776271])

array([111.18746422, 102.01776271])

array([100.        ,  59.87540544,  47.06910857])

array([59.87540544, 47.06910857])

array([100.        ,  57.80023703,  64.95883829])

array([57.80023703, 64.95883829])

array([100.        , 123.24612709, 111.04708332])

array([123.24612709, 111.04708332])

array([100.        , 134.60020183, 115.36142965])

array([134.60020183, 115.36142965])

array([100.        ,  94.26866973, 102.37782219])

array([ 94.26866973, 102.37782219])

array([100.        ,  62.62496122,  49.80254077])

array([62.62496122, 49.80254077])

array([100.        , 102.15496986,  80.19616723])

array([102.15496986,  80.19616723])

array([100.        , 126.44576628, 134.15089517])

array([126.44576628, 134.15089517])

array([100.        ,  97.25293703, 121.35535009])

array([ 97.25293703, 121.35535009])

array([100.        , 114.2569109 , 159.37932495])

array([114.2569109 , 159.37932495])

array([100.        ,  94.04547873, 105.89157123])

array([ 94.04547873, 105.89157123])

array([100.        , 103.71687173,  92.11329075])

array([103.71687173,  92.11329075])

array([100.        , 123.68198453, 173.50053539])

array([123.68198453, 173.50053539])

array([100.        ,  89.82275583,  31.2386608 ])

array([89.82275583, 31.2386608 ])

array([100.        , 100.30454675,  68.29505449])

array([100.30454675,  68.29505449])

array([100.        ,  80.26848552,  79.08610997])

array([80.26848552, 79.08610997])

array([100.        ,  81.48627212,  96.95920342])

array([81.48627212, 96.95920342])

array([100.        , 105.55085557, 126.872689  ])

array([105.55085557, 126.872689  ])

array([100.        , 122.6608316 ,  98.49944699])

array([122.6608316 ,  98.49944699])

array([100.        , 119.98110219, 132.86124842])

array([119.98110219, 132.86124842])

array([100.        ,  92.2940338 , 106.89191706])

array([ 92.2940338 , 106.89191706])

array([100.        , 128.8775816 , 100.14037882])

array([128.8775816 , 100.14037882])

array([100.        , 134.96895288,  82.85466243])

array([134.96895288,  82.85466243])

array([100.        , 105.18580522, 118.35284989])

array([105.18580522, 118.35284989])

array([100.        ,  80.57103286,  75.23416503])

array([80.57103286, 75.23416503])

array([100.        , 104.10836208, 105.87864699])

array([104.10836208, 105.87864699])

array([100.        , 125.53600786, 140.75555944])

array([125.53600786, 140.75555944])

array([100.        , 149.23088674, 127.46131306])

array([149.23088674, 127.46131306])

array([100.        , 114.1103159 ,  99.08715991])

array([114.1103159 ,  99.08715991])

array([100.        ,  93.21100849,  83.90034723])

array([93.21100849, 83.90034723])

array([100.        , 112.83737354,  49.67737896])

array([112.83737354,  49.67737896])

array([100.        , 127.70688214, 128.07145999])

array([127.70688214, 128.07145999])

array([100.        ,  66.07550718,  71.41743459])

array([66.07550718, 71.41743459])

array([100.        ,  72.64552874,  58.95674139])

array([72.64552874, 58.95674139])

array([100.        ,  97.47488635, 116.80656141])

array([ 97.47488635, 116.80656141])

array([100.        , 109.87986479, 116.01521154])

array([109.87986479, 116.01521154])

array([100.        , 112.32720941, 111.24316474])

array([112.32720941, 111.24316474])

array([100.        ,  57.83484519,  62.81980458])

array([57.83484519, 62.81980458])

array([100.        , 123.2706456 ,  87.00781966])

array([123.2706456 ,  87.00781966])

array([100.        ,  98.97329936, 117.91761013])

array([ 98.97329936, 117.91761013])

array([100.        , 107.61567556,  74.92486162])

array([107.61567556,  74.92486162])

63.29472008102475